version: '3.7'

services: 
  web:
    build: 
      context: ./app
      target: development
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file: .env
    environment:
      DEBUG: 0

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_DB: ${SQL_DATABASE}

volumes:
  postgres_data:
