name: Testing
on:
  push:
    branches:
      - "**"
  pull_request:
jobs:
  test:
    name: Run full test suite
    runs-on: ubuntu-latest
    env: 
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: directory
      SQL_USER: developer
      SQL_PASSWORD: password
      SQL_HOST: db
      SQL_PORT: 5432
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_DATABASE: directory
          POSTGRES_USER: developer
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Run database migrations
        run: python app/manage.py migrate
      - name: Django Tests 
        run: python app/manage.py test
